
name: Workflow Update

on:
  push:
      branches: [ main ]
  pull_request:

jobs:
  setup-tests:
    runs-on: ubuntu-latest
    outputs:
      notebook-fpaths: ${{ steps.set-notebook-fpaths.outputs.notebook-fpaths }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          # cache: 'pip'

      - name: Cache Python deps
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ env.pythonLocation }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.pythonLocation }}-pip-
            ${{ runner.os }}-${{ env.pythonLocation }}-

      # - name: Install requirements
      #   run: |
      #     pip install --upgrade pip
      #     pip install -r requirements.txt

      - name: Check for notebook output
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1

      - name: Test for API keys in docs
        run: |
          pip install typing_extensions  ## <3.8
          python scripts/detect_secrets.py -d -p workflows -s

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v19
        with:
          quotepath: "false"
          since_last_remote_commit: 'true'
          files: |
            **/*.ipynb

      - id: set-notebook-fpaths
        name: Setting notebook fpath output
        run: |
          DIFF_NOTEBOOKS=$(for n in ${{ steps.changed-files.outputs.all_changed_files }}; do echo $n; done | grep '.ipynb' | sed  s/'workflows\/'//g )
          echo $DIFF_NOTEBOOKS
          NOTEBOOKS=$(cat 'workflows/.workflowsignore' | grep '#' | sed 's/# //g')

          NOTEBOOK_FPATHS=$( grep -Fx "$NOTEBOOKS" <<< "$DIFF_NOTEBOOKS" | jq -Rsc '. / "\n" - [""]' )
          echo $NOTEBOOK_FPATHS

          echo "::set-output name=notebook-fpaths::$NOTEBOOK_FPATHS"


  test-notebooks:
    name: Test ${{ matrix.notebook }}
    needs: setup-tests
    if: ${{ needs.setup-tests.outputs.notebook-fpaths }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest]
        python-version: [ '3.8' ]
        # python-version: [ '3.6', '3.7', '3.8', '3.9' ]
        notebook: ${{fromJSON(needs.setup-tests.outputs.notebook-fpaths)}}
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
          # - os: macos-latest
          #   path: ~/Library/Caches/pip
          # - os: windows-latest
          #   path: ~\AppData\Local\pip\Cache
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          # cache: 'pip'
      - name: Cache Python deps
        uses: actions/cache@v2
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-${{ env.pythonLocation }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.pythonLocation }}-pip-
            ${{ runner.os }}-${{ env.pythonLocation }}-

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install pyyaml
          python -m pip install -e .[tests]
          jupyter kernelspec list

      - name: Test notebooks
        # continue-on-error: true
        env:
          TEST_ACTIVATION_TOKEN: ${{ secrets.SUPPORT_ACTIVATION_TOKEN }}
          WORKFLOW_TOKEN_CLUSTER_YOUR_DATA_WITH_RELEVANCE_AI: ${{ secrets.WORKFLOW_TOKEN_CLUSTER_YOUR_DATA_WITH_RELEVANCE_AI }}
          WORKFLOW_TOKEN_VECTORIZE_YOUR_DATA_WITH_RELEVANCE_AI: ${{ secrets.WORKFLOW_TOKEN_VECTORIZE_YOUR_DATA_WITH_RELEVANCE_AI }}
          WORKFLOW_TOKEN_REDUCE_THE_DIMENSIONS_OF_YOUR_DATA_WITH_RELEVANCE_AI: ${{ secrets.WORKFLOW_TOKEN_REDUCE_THE_DIMENSIONS_OF_YOUR_DATA_WITH_RELEVANCE_AI }}
          WORKFLOW_TOKEN_CORE_SUBCLUSTERING:  ${{ secrets.WORKFLOW_TOKEN_CORE_SUBCLUSTERING }}
        run: |
          python scripts/test_notebooks.py --notebooks ${{ matrix.notebook }}
