name: Upload to S3

on:
  push:
      branches: [ main, development ]
  pull_request:

jobs:
  upload:
    name: Upload new notebooks to S3
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set branch name
      run: |
        echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Set branch name in PR
      if: ${{ github.event.pull_request }}
      run: |
        echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV

    - name: Set environment var based on branch name
      id: set-environment
      run: |
        echo $BRANCH_NAME
        BRANCH_NAME="main"
        if [[ $BRANCH_NAME == "main" ]]; then
          export ENVIRONMENT="prod"
        else
          export ENVIRONMENT="development"
        fi

        echo "##[set-output name=environment;]$(echo $ENVIRONMENT)"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}


    - name: Upload to S3
      run: |
        ENVIRONMENT=${{ steps.set-environment.outputs.environment }}
        echo "Uploading notebooks to S3"

        aws s3 cp workflows s3://relevance-${ENVIRONMENT}-ap-southeast-2-workflows/workflows/notebooks/ --recursive

        if [[ $ENVIRONMENT == "prod" ]]; then
          aws s3 cp workflows s3://relevance-${ENVIRONMENT}-us-east-1-workflows/workflows/notebooks/ --recursive
        fi
