name: Upload to S3

on:
  push:
      branches: [ main, development ]
  pull_request:

jobs:
  upload:
    name: Upload new notebooks to S3
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set branch name
      run: |
        echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Set branch name in PR
      if: ${{ github.event.pull_request }}
      run: |
        echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set environment var based on branch name
      id: set-environment
      run: |
        echo $BRANCH_NAME
        if [[ $BRANCH_NAME == "main" ]]; then
          aws s3 cp workflows s3://relevance-production-ap-southeast-2-workflows/workflows/notebooks/ --recursive
          aws s3 cp workflows s3://relevance-production-us-east-1-workflows/workflows/notebooks/ --recursive
        fi

        echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
