name: Upload to S3

on:
  push:
      branches: [ main, development ]
  pull_request:


jobs:
  upload:
    name: Upload to s3
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set Github env var based on branch name
      id: set-environment
      run: |
        BRANCH_NAME=${{ github.head_ref }}
        echo $BRANCH_NAME
        if [[ $BRANCH_NAME == "main" ]]; then
          export ENVIRONMENT="prod"
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        elif [[ $BRANCH_NAME == "development" ]]; then
          export ENVIRONMENT="dev"
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        else
          export ENVIRONMENT="sandbox"
          export AWS_ACCESS_KEY_ID=${{ secrets.SANDBOX_AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.SANDBOX_AWS_SECRET_ACCESS_KEY }}
        fi

        echo $ENVIRONMENT

        echo "##[set-output name=environment;]$(echo $ENVIRONMENT)"
        echo "::set-output name=short-sha::$(git rev-parse --short ${{ github.sha }})"
        echo "::set-output name=aws_access_key_id::$(echo $AWS_ACCESS_KEY_ID)"
        echo "::set-output name=aws_secret_access_key::$(echo $AWS_SECRET_ACCESS_KEY)"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ steps.set-environment.outputs.aws_access_key_id }}
        aws-secret-access-key: ${{ steps.set-environment.outputs.aws_secret_access_key }}
        aws-region: ${{ matrix.region }}

    - name: Upload to S3
      run: |
        aws s3 cp workflows s3://relevance-${ENVIRONMENT}-ap-southeast-2-workflows/workflows/notebooks/ --recursive

        if [[ $ENVIRONMENT == "prod" ]]; then
          aws s3 cp workflows s3://relevance-${ENVIRONMENT}-us-east-1-workflows/workflows/notebooks/ --recursive
